persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Allow unlimited connections
max_connections -1

listener 1883
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true
